[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 16

[studio]
port = 54323
api_url = "http://localhost"

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = false
